articles/urls.py
from django.conf.urls import url
from .views import article_list, article_detail, article_create, article_update, article_delete


urlpatterns = [
    url(r'^$', article_list, name='list'),
    url(r'^create/$', article_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', article_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/update/$', article_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', article_delete, name='delete'),
]

cms/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

admin.site.site_header = 'Panel de Control : Famisoft'

admin.site.site_title = 'Famisoft Software y Desarrollo a la Medida'

urlpatterns = [
    url(r'^', include('web.urls', namespace="web")),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include("articles.urls", namespace="article")),
    url(r'^products/', include("products.urls", namespace="product")),
    url(r'^categories/', include("products.urls_categories", namespace="category")),
    url(r'^newsletter/', include("newsletters.urls", namespace="newsletter")),
    url(r'^games/', include("games.urls", namespace="game")),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/tags/javascript.html
{% load staticfiles %}
<script src="{% static "js/vendor/jquery/jquery-3.1.1.min.js" %}"></script>
<script src="{% static "js/flat-ui.min.js" %}"></script>
<script src="{% static "js/vendor/video.js" %}"></script>

templates/tags/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="alert alert-dismissable
            {% if "success" in message.tags %}alert-success {% endif %}
            {% if "info" in message.tags %}alert-info {% endif %}
            {% if "debug" in message.tags %}alert-warning {% endif %}
            {% if "warning" in message.tags %}alert-warning {% endif %}
            {% if "error" in message.tags %}alert-danger {% endif %}
            {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
        </li>
        {% endfor %}
    </ul>
{% endif %}

templates/tags/product-search.html
<form action="{% url 'product:list' %}" method="GET">
    <input type="text" class="form-control" placeholder="Búsqueda" name="q">
    <button class="btn btn-default">Buscar</button>
</form>

<br>

templates/tags/product-thumbnail.html
<div class="thumbnail">
    {% if photo == True %}
    <a href="{{ product.get_absolute_url }}">
        <img src="{{ product.get_image_url }}" class="img-responsive" alt="{{ product.title }}">
    </a>
    {% endif %}
    <div class="caption">
    <h3>
        <a href="{{ product.get_absolute_url }}">
            {{ product.title|truncatechars:50 }}
        </a>
    </h3>
    <p>{{ product.description|linebreaks|truncatechars:160 }}</p>

    {% if price == True %}
        {{ product.variation_set.first.get_html_price }}
    {% endif %}
    <p>
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">Ver</a>
    </p>
</div>
</div>

templates/tags/style.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/normalize.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "css/flat-ui.min.css" %}">
<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
<link rel="stylesheet" href="{% static "css/base.css" %}">